### ISSUE TITLE
go mod download fails

### ISSUE THREAD

**Issue by regel** [AlfonsoCebollero/asyncReply-RequestAPI#1]
The project contains unresolved dependencies, causing `go mod download` to fail.

```
$ go mod download
go: github.com/fati/structtag@v1.2.0: reading github.com/fati/structtag/go.mod at revision v1.2.0:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

This line in `go.mod` is problematic. fati/structtag v1.2.0 does not exist. However, fatih/structtag v1.2.0 does.

$ grep struct go.mod 
	github.com/fati/structtag v1.2.0 // indirect

You may want to investigate to find out what pulls this dependency in the buld and tidy your go mod.

Adding a Dockerfile to build your app is also a good idea to help replicate the build.

**Comment by AlfonsoCebollero** [comment]
Hello Sebastien!

Thank you for the feedback. I have fixed the dependencies and added a
Dockerfile as well as more information about the configuration of the
application in the Readme.
I hope everything is ready to go now.

If you encounter any issues please let me know.
Best regards.

Alfonso Cebollero
